export const testConfig = {
  copyright: {
    searchText: 'Copyright',
    text: '2010',
    linkText: 'Free For Charity Hosting',
    linkUrl: null,
  },
  cookieConsent: {
    bannerHeading: 'We Value Your Privacy',
    modalHeading: 'Cookie Preferences',
    buttons: {
      acceptAll: 'Accept All',
      declineAll: 'Decline All',
      customize: 'Customize',
      savePreferences: 'Save Preferences',
      cancel: 'Cancel',
    },
  },
  navigation: {
    homeUrl: '/',
    searchLabel: 'Search this site (opens in new tab)',
  },
  // Must match the PAGES array in .github/workflows/ci.yml (build title verification)
  pages: [
    '/',
    '/who-i-am/',
    '/charity/',
    '/walk-and-talk/',
    '/professional-development/',
    '/industry-conferences/',
    '/psu-arl-referral/',
    '/wgu-referral/',
    '/education/',
    '/education/wgu/',
    '/education/cochise-college/',
    '/education/umuc/',
    '/education/smeal-dba/',
    '/certification/',
    '/fun/',
    '/quotes/',
    '/resume/',
    '/learn-free-charity/',
    '/personal-project-manager/',
    '/clarke-moyer-world-famous-apple-crisp-recipe/',
    '/clarke-moyer-sweet-tea-recipe/',
    '/clarke-moyer-philly-cheesesteak-recipe/',
    '/cooking/',
    '/affiliate-disclosure/',
    '/privacy-policy/',
    '/cookie-policy/',
    // Certification guides
    '/clarke-moyer-cissp-certification-passing-guide/',
    '/clarke-moyer-cissp-issep-certification-passing-guide/',
    '/clarke-moyer-ciw-professional-passing-guide/',
    '/clarke-moyer-comptia-a-plus-passing-guide/',
    '/clarke-moyer-comptia-network-plus-passing-guide/',
    '/clarke-moyer-comptia-project-plus-passing-guide/',
    '/clarke-moyer-comptia-security-plus-passing-guide/',
    '/clarke-moyer-itil-4-foundation-passing-guide/',
    '/clarke-moyer-mcp-passing-guide/',
    '/clarke-moyer-microsoft-ai-900-passing-guide/',
    '/clarke-moyer-microsoft-az-500-passing-guide/',
    '/clarke-moyer-microsoft-az-900-passing-guide/',
    '/clarke-moyer-microsoft-ms-900-passing-guide/',
    '/clarke-moyer-microsoft-sc-500-passing-guide/',
    '/clarke-moyer-microsoft-sc-900-passing-guide/',
    '/clarke-moyer-pmp-certification-passing-guide/',
    '/clarke-moyer-safe-spc-certification-passing-guide/',
    '/clarke-moyer-vcp4-dcv-passing-guide/',
    '/clarke-moyer-vcp5-dcv-passing-guide/',
    '/clarke-moyer-vcp6-cma-passing-guide/',
    '/clarke-moyer-vcp-am-passing-guide/',
    '/contact/',
    '/404',
  ],
}
