export const testConfig = {
  copyright: {
    searchText: 'Copyright',
    text: '2010',
    linkText: 'Free For Charity Hosting',
    linkUrl: null,
  },
  cookieConsent: {
    bannerHeading: 'We Value Your Privacy',
    modalHeading: 'Cookie Preferences',
    buttons: {
      acceptAll: 'Accept All',
      declineAll: 'Decline All',
      customize: 'Customize',
      savePreferences: 'Save Preferences',
      cancel: 'Cancel',
    },
  },
  navigation: {
    homeUrl: '/',
    searchLabel: 'Search this site (opens in new tab)',
  },
  // Must match the PAGES array in .github/workflows/ci.yml (build title verification)
  pages: [
    '/',
    '/who-i-am/',
    '/free-for-charity/',
    '/walk-and-talk/',
    '/professional-development/',
    '/industry-conferences/',
    '/psu-arl-referral-program/',
    '/wgu-referral-program/',
    '/certification-guides/',
    '/fun/',
    '/quotes/',
    '/it-project-management-resume-of-clarke-moyer/',
    '/western-governors-university-bs-it/',
    '/learn-free-charity/',
    '/personal-project-manager/',
    '/clarke-moyer-world-famous-apple-crisp-recipe/',
    '/clarke-moyer-sweet-tea-recipe/',
    '/clarke-moyer-philly-cheesesteak-recipe/',
    '/cooking/',
    '/affiliate-disclosure/',
    '/privacy-policy/',
    '/cookie-policy/',
  ],
}
