import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Privacy Policy for clarkemoyer.com',
}

const EFFECTIVE_DATE = 'April 27, 2026'

export default function PrivacyPolicy() {
  return (
    <>
      <div className="max-w-4xl mx-auto px-6 py-16 mt-20">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-8">
          <em>Effective Date: {EFFECTIVE_DATE}</em>
        </p>

        <div className="prose prose-gray max-w-none space-y-8">

          <section>
            <h2 className="text-xl font-bold text-gray-900">1. Overview</h2>
            <p className="text-gray-700">
              This is the personal and professional website of Clarke Moyer at{' '}
              <a href="https://clarkemoyer.com" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">
                clarkemoyer.com
              </a>
              . The site offers information about Clarke&apos;s background, writing, and paid consulting services
              (Walk and Talk). This policy explains what data is collected, by whom, and how it is used. Plain
              language is the goal — no boilerplate walls.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">2. What This Site Does NOT Collect</h2>
            <p className="text-gray-700">
              This website has no contact forms. It does not collect your name, email address, or any other
              personal information directly. There is no account system, no newsletter signup, and no login.
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-1 mt-2">
              <li>
                <strong>Text messages to (520) 222-8104</strong> — handled by your carrier and Clarke&apos;s phone.
                Not stored by this website.
              </li>
              <li>
                <strong>LinkedIn messages or connection requests</strong> — governed by{' '}
                <a href="https://www.linkedin.com/legal/privacy-policy" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">
                  LinkedIn&apos;s Privacy Policy
                </a>
                .
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">3. Walk and Talk Consulting</h2>
            <p className="text-gray-700">
              Walk and Talk is a paid consulting service ($750/hr) booked through Microsoft Bookings. Here is
              how data flows through that process:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mt-2">
              <li>
                <strong>Booking data (name, email, scheduling info)</strong> — collected and stored by{' '}
                <a href="https://www.microsoft.com/en-us/trust-center/privacy" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">
                  Microsoft
                </a>
                , not by this website. Microsoft&apos;s privacy policy governs how that data is handled.
              </li>
              <li>
                <strong>Call recording and transcription</strong> — Walk and Talk sessions are conducted via
                Microsoft Teams Premium. Teams Premium automatically records and transcribes calls and generates
                an AI-powered summary of the session.
              </li>
              <li>
                <strong>AI call summary</strong> — the summary generated by Microsoft Teams Premium is delivered
                to you (the client) via Teams after the session. It is not published or shared with anyone else.
              </li>
            </ul>
            <p className="text-gray-700 mt-2">
              By booking a Walk and Talk session, you acknowledge that the call will be recorded and transcribed
              by Microsoft Teams Premium.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">4. Analytics</h2>
            <p className="text-gray-700">
              With your consent, this site uses Google Analytics 4 (GA4), loaded via Google Tag Manager (GTM).
              GA4 collects aggregated, anonymized traffic data — pages visited, general location (country/region),
              device type, and referral source. No personally identifiable information is tracked.
            </p>
            <p className="text-gray-700 mt-2">
              Analytics are <strong>only activated if you accept analytics cookies</strong>. If you decline,
              GTM is notified and GA4 does not fire. You can change your preference at any time via the
              &quot;Cookie Preferences&quot; link in the site footer.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">5. Cookies</h2>
            <p className="text-gray-700">
              See the{' '}
              <a href="/cookie-policy" className="text-blue-600 hover:underline">
                Cookie Policy
              </a>{' '}
              for full details. In short: necessary cookies store your consent preference; analytics cookies
              are only set if you opt in.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">6. Affiliate Links</h2>
            <p className="text-gray-700">
              Some links on this site are Amazon affiliate links (tag: <code>clarkemoyer-20</code>). If you
              click an affiliate link and make a purchase, Clarke may earn a small commission at no extra cost
              to you. Affiliate links are disclosed in accordance with FTC guidelines — see the{' '}
              <a href="/affiliate-disclosure" className="text-blue-600 hover:underline">
                Affiliate Disclosure
              </a>{' '}
              for more detail.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">7. Third-Party Services Summary</h2>
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-gray-700 border-collapse mt-2">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="text-left p-3 border border-gray-200 font-semibold">Service</th>
                    <th className="text-left p-3 border border-gray-200 font-semibold">Purpose</th>
                    <th className="text-left p-3 border border-gray-200 font-semibold">Data Handled By</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="p-3 border border-gray-200">Microsoft Bookings</td>
                    <td className="p-3 border border-gray-200">Consulting scheduling</td>
                    <td className="p-3 border border-gray-200">
                      <a href="https://www.microsoft.com/en-us/trust-center/privacy" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">Microsoft</a>
                    </td>
                  </tr>
                  <tr className="bg-gray-50">
                    <td className="p-3 border border-gray-200">Microsoft Teams Premium</td>
                    <td className="p-3 border border-gray-200">Call recording, transcription, AI summary</td>
                    <td className="p-3 border border-gray-200">
                      <a href="https://www.microsoft.com/en-us/trust-center/privacy" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">Microsoft</a>
                    </td>
                  </tr>
                  <tr>
                    <td className="p-3 border border-gray-200">Google Analytics 4 (via GTM)</td>
                    <td className="p-3 border border-gray-200">Anonymous site traffic analytics (consent-gated)</td>
                    <td className="p-3 border border-gray-200">
                      <a href="https://policies.google.com/privacy" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">Google</a>
                    </td>
                  </tr>
                  <tr className="bg-gray-50">
                    <td className="p-3 border border-gray-200">Amazon Associates</td>
                    <td className="p-3 border border-gray-200">Affiliate links (disclosed)</td>
                    <td className="p-3 border border-gray-200">
                      <a href="https://www.amazon.com/gp/help/customer/display.html?nodeId=GX7NJQ4ZB8MHFRNJ" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">Amazon</a>
                    </td>
                  </tr>
                  <tr>
                    <td className="p-3 border border-gray-200">Free For Charity</td>
                    <td className="p-3 border border-gray-200">Nonprofit referrals (separate site)</td>
                    <td className="p-3 border border-gray-200">
                      <a href="https://freeforcharity.org" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">freeforcharity.org</a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">8. Your Rights</h2>
            <p className="text-gray-700">
              You can update your cookie consent at any time using the &quot;Cookie Preferences&quot; link in the
              site footer. You may also clear your browser storage to remove any stored preferences. For questions
              about data held by Microsoft (Bookings/Teams) or Google (Analytics), contact those services directly
              through their respective privacy portals.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900">9. Contact</h2>
            <p className="text-gray-700">
              Questions about this policy? Reach Clarke via{' '}
              <a
                href="https://www.linkedin.com/in/clarkemoyer"
                className="text-blue-600 hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                LinkedIn
              </a>{' '}
              or text <a href="sms:+15202228104" className="text-blue-600 hover:underline">(520) 222-8104</a>.
            </p>
          </section>

        </div>
      </div>
    </>
  )
}
